export const AI_SCHEMA_VERSION = '1.3.0';

export type AIFieldPage = 'cover' | 'media' | 'reference' | 'condition' | 'value' | 'publishing';
export type AIFieldDataType =
  | 'text'
  | 'long_text'
  | 'date'
  | 'number'
  | 'money'
  | 'percentage'
  | 'enum'
  | 'url'
  | 'boolean'
  | 'file'
  | 'media_tags'
  | 'computed';
export type AIFieldCardinality = 'single' | 'repeatable' | 'computed';
export type AIFieldConfidentiality = 'public' | 'community' | 'secret';
export type AIFieldSourceKind =
  | 'user'
  | 'document'
  | 'file_metadata'
  | 'manufacturer'
  | 'expert'
  | 'market'
  | 'calculation';

export interface AIFieldDescriptor {
  id: string;
  page: AIFieldPage;
  section: string;
  label: string;
  purpose: string;
  instructions: string;
  dataType: AIFieldDataType;
  cardinality: AIFieldCardinality;
  required: boolean;
  confidentiality: AIFieldConfidentiality;
  sourcePriority: readonly AIFieldSourceKind[];
  validation: string;
  examples?: readonly string[];
  allowedValues?: readonly string[];
  dependencies?: readonly string[];
  aiWritable: boolean;
  humanReviewRequired: boolean;
  emptyValuePolicy: 'leave_blank' | 'mark_unknown' | 'not_applicable' | 'compute_only';
}

const field = <const T extends AIFieldDescriptor>(descriptor: T) => descriptor;

/**
 * Référentiel canonique des postes du Cartulaire.
 *
 * Une IA doit produire des propositions qui référencent ces identifiants stables.
 * Les identifiants des collections se terminant par [] décrivent une famille de
 * champs ; l'instance réelle est transmise séparément par `data-ai-instance`.
 */
export const AI_FIELD_CATALOG = [
  field({ id: 'cover.asset.type', page: 'cover', section: 'asset', label: 'Type de bien', purpose: 'Qualifier la nature du bien documenté par le Cartulaire.', instructions: 'Sélectionner uniquement la catégorie confirmée par le propriétaire. Utiliser Autre ou Autre art lorsqu’aucune catégorie plus précise ne convient.', dataType: 'enum', cardinality: 'single', required: true, confidentiality: 'public', sourcePriority: ['user', 'document'], validation: 'Valeur comprise dans la liste autorisée et cohérente avec le bien décrit.', allowedValues: ['Montre', 'Voiture', 'Vin', 'Sculpture', 'Peinture', 'Photographie', 'Meuble', 'Autre art', 'Bien immobilier', 'Autre'], aiWritable: false, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.watch.brand', page: 'cover', section: 'watch', label: 'Marque', purpose: 'Identifier le fabricant de la montre.', instructions: 'Reprendre la marque telle qu’elle apparaît sur la montre, les papiers ou une archive fiable. Ne pas la déduire d’un simple nom de fichier.', dataType: 'text', cardinality: 'single', required: true, confidentiality: 'public', sourcePriority: ['document', 'manufacturer', 'expert', 'user'], validation: 'Nom de marque sans slogan ni nom de modèle.', examples: ['IWC Schaffhausen'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'cover.watch.model', page: 'cover', section: 'watch', label: 'Nom de la montre', purpose: 'Donner le nom commercial lisible de la montre.', instructions: 'Utiliser le nom officiel du modèle ou de la collection. Conserver la référence dans le poste dédié.', dataType: 'text', cardinality: 'single', required: true, confidentiality: 'public', sourcePriority: ['manufacturer', 'document', 'expert', 'user'], validation: 'Nom court, sans valeur, état ni argument commercial.', examples: ['Flieger UTC'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'cover.watch.reference', page: 'cover', section: 'watch', label: 'Numéro de référence', purpose: 'Identifier précisément la variante de référence.', instructions: 'Recopier la référence complète avec ses séparateurs. Signaler toute divergence entre boîtier, papiers et sources.', dataType: 'text', cardinality: 'single', required: true, confidentiality: 'public', sourcePriority: ['document', 'manufacturer', 'expert', 'user'], validation: 'Référence exacte ; aucune normalisation destructive.', examples: ['IW3251-001'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'cover.watch.status', page: 'cover', section: 'watch', label: 'Statut patrimonial', purpose: 'Exprimer l’intention actuelle du propriétaire pour la montre.', instructions: 'Choisir uniquement le statut explicitement décidé par le propriétaire. Ne jamais déduire une intention de vente d’une valorisation ou d’une publication.', dataType: 'enum', cardinality: 'single', required: true, confidentiality: 'public', sourcePriority: ['user'], validation: 'Valeur comprise dans la liste autorisée.', allowedValues: ['Patrimonial', 'À vendre', 'Ouvert à proposition'], aiWritable: false, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.owner.type', page: 'cover', section: 'owner', label: 'Type de propriétaire', purpose: 'Adapter les données d’identification au détenteur.', instructions: 'Choisir Personne physique ou Entreprise uniquement à partir des informations explicites du dossier.', dataType: 'enum', cardinality: 'single', required: true, confidentiality: 'secret', sourcePriority: ['document', 'user'], validation: 'Valeur comprise dans la liste autorisée.', allowedValues: ['Personne physique', 'Entreprise'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.owner.customFields[].label', page: 'cover', section: 'owner', label: 'Catégorie propriétaire', purpose: 'Nommer une information d’identité ou de contact.', instructions: 'Créer une catégorie courte et non ambiguë. Réutiliser une catégorie existante avant d’en créer une nouvelle.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['document', 'user'], validation: 'Libellé unique dans la fiche propriétaire.', examples: ['Raison sociale', 'Numéro d’immatriculation'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.owner.customFields[].value', page: 'cover', section: 'owner', label: 'Valeur propriétaire', purpose: 'Conserver la valeur correspondant à une catégorie propriétaire.', instructions: 'Transcrire fidèlement la source. Ne pas compléter une adresse, un email ou un téléphone par supposition.', dataType: 'long_text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['document', 'user'], validation: 'La valeur doit correspondre au libellé de la même instance.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.owner.documents[].category', page: 'cover', section: 'owner_documents', label: 'Catégorie du document propriétaire', purpose: 'Qualifier une pièce confidentielle.', instructions: 'Choisir une catégorie descriptive sans extraire plus de données personnelles que nécessaire.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['document', 'user'], validation: 'Catégorie courte ; ne jamais rendre publique automatiquement.', examples: ['Passeport', 'Extrait Kbis'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.owner.documents[].fileName', page: 'cover', section: 'owner_documents', label: 'Nom du fichier propriétaire', purpose: 'Donner un nom exploitable à la pièce jointe.', instructions: 'Conserver l’extension et éviter d’inscrire des données sensibles inutiles dans le nom.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['file_metadata', 'user'], validation: 'Nom de fichier non vide avec extension si elle est connue.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.owner.documents[].file', page: 'cover', section: 'owner_documents', label: 'Fichier propriétaire', purpose: 'Associer la pièce source à la fiche du propriétaire.', instructions: 'Importer le fichier original sans le modifier, calculer son empreinte et conserver le type MIME.', dataType: 'file', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'file_metadata'], validation: 'Fichier lisible, empreinte calculée, accès secret.', aiWritable: false, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.transmission.recipients[].firstName', page: 'cover', section: 'transmission', label: 'Prénom de la personne désignée', purpose: 'Identifier une personne envisagée pour la transmission.', instructions: 'Transcrire uniquement le prénom fourni par le propriétaire ou une pièce autorisée.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'document'], validation: 'Prénom rattaché à la bonne personne ; aucune identité déduite.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.transmission.recipients[].lastName', page: 'cover', section: 'transmission', label: 'Nom de la personne désignée', purpose: 'Identifier une personne envisagée pour la transmission.', instructions: 'Transcrire uniquement le nom fourni par le propriétaire ou une pièce autorisée.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'document'], validation: 'Nom rattaché à la bonne personne ; aucune identité déduite.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.transmission.recipients[].address', page: 'cover', section: 'transmission', label: 'Adresse de la personne désignée', purpose: 'Conserver l’adresse de contact utile au projet de transmission.', instructions: 'Transcrire fidèlement l’adresse fournie sans compléter les éléments manquants par supposition.', dataType: 'long_text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'document'], validation: 'Adresse rattachée à la bonne personne et conservée au niveau Secret par défaut.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.transmission.recipients[].email', page: 'cover', section: 'transmission', label: 'Email de la personne désignée', purpose: 'Conserver un moyen de contact électronique.', instructions: 'Reprendre l’adresse email explicitement fournie ; ne pas reconstruire une adresse supposée.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'document'], validation: 'Format email valide et rattachement à la bonne personne.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.transmission.recipients[].phone', page: 'cover', section: 'transmission', label: 'Téléphone de la personne désignée', purpose: 'Conserver un numéro de contact.', instructions: 'Reprendre le numéro explicitement fourni, avec indicatif international lorsqu’il est disponible.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'document'], validation: 'Numéro plausible et rattaché à la bonne personne.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.transmission.recipients[].percentage', page: 'cover', section: 'transmission', label: 'Pourcentage donné', purpose: 'Exprimer la part du bien que le propriétaire souhaite transmettre à cette personne.', instructions: 'Utiliser uniquement le pourcentage décidé par le propriétaire. Ne pas interpréter ce champ comme un acte juridique exécuté.', dataType: 'percentage', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'document'], validation: 'Nombre compris entre 0 et 100 ; cohérence globale des parts à faire confirmer par le propriétaire.', aiWritable: false, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.storage.locations[].name', page: 'cover', section: 'storage', label: 'Lieu de stockage', purpose: 'Identifier séparément chaque emplacement où un élément du dossier est conservé.', instructions: 'Nommer le type de lieu et la zone utile sans révéler de code, de consigne d’accès ni d’adresse précise hors du niveau Secret.', dataType: 'text', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['user', 'document'], validation: 'Lieu distinct, compréhensible et rattaché à la bonne instance.', examples: ['Coffre bancaire', 'Cave du domicile'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.storage.locations[].contents', page: 'cover', section: 'storage', label: 'Contenu stocké', purpose: 'Préciser ce qui est conservé dans chaque lieu.', instructions: 'Lister uniquement les éléments réellement stockés dans cet emplacement, par exemple montre, boîte, papiers ou accessoires.', dataType: 'long_text', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['user', 'document'], validation: 'Contenu explicite et non dupliqué entre lieux sauf si la répartition est expliquée.', examples: ['Montre', 'Boîte et surboîte'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'cover.storage.locations[].description', page: 'cover', section: 'storage', label: 'Description et conditions de stockage', purpose: 'Documenter les conditions de conservation propres à chaque emplacement.', instructions: 'Décrire la sécurité, l’accès, la température, l’humidité ou toute remarque utile sans enregistrer de secret opérationnel.', dataType: 'long_text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'document', 'expert'], validation: 'Texte factuel, sans code de sécurité ni instruction d’accès exploitable.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),

  field({ id: 'media.assets[].file', page: 'media', section: 'library', label: 'Actif média', purpose: 'Importer une image, vidéo, séquence, archive ou document source.', instructions: 'Conserver l’original, le type MIME, la taille, le nom, les métadonnées et une empreinte. Ne jamais modifier silencieusement le fichier.', dataType: 'file', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'file_metadata'], validation: 'Empreinte et métadonnées techniques disponibles ; type autorisé par le coffre média.', aiWritable: false, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'media.assets[].name', page: 'media', section: 'library', label: 'Nom de l’actif', purpose: 'Identifier humainement un actif média.', instructions: 'Créer un nom descriptif court à partir du contenu observé, sans modifier le nom de fichier original.', dataType: 'text', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['file_metadata', 'user'], validation: 'Nom distinct du fichier original et sans conclusion non vérifiée.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'media.assets[].tags', page: 'media', section: 'library', label: 'Catégories média', purpose: 'Déterminer les emplacements du site où l’actif peut apparaître.', instructions: 'Attribuer un ou plusieurs tags selon le contenu et l’usage voulu. Une seule photo principale et une seule vidéo principale doivent être proposées à la fois.', dataType: 'media_tags', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'file_metadata'], validation: 'Tags dans la liste autorisée ; conflits de rôle signalés.', allowedValues: ['Photo principale', 'Vidéo principale', 'Séquence 3D', 'Diaporama', 'Accessoires', 'Documentation', 'Autres'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'media.assets[].metadataTimestamp', page: 'media', section: 'library', label: 'Horodatage du média', purpose: 'Dater la capture ou, à défaut, le fichier.', instructions: 'Lire en priorité EXIF/QuickTime/XMP ; sinon utiliser lastModified et enregistrer la source exacte. Ne pas inventer une heure.', dataType: 'date', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['file_metadata'], validation: 'ISO 8601 avec fuseau si connu et provenance conservée.', aiWritable: false, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'media.assets[].hash', page: 'media', section: 'library', label: 'Empreinte du média', purpose: 'Garantir l’identité binaire et détecter les doublons.', instructions: 'Calculer l’empreinte sur les octets originaux ; ne jamais saisir ou extrapoler une empreinte.', dataType: 'computed', cardinality: 'computed', required: true, confidentiality: 'secret', sourcePriority: ['calculation'], validation: 'Empreinte produite par le moteur d’intégrité.', aiWritable: false, humanReviewRequired: false, emptyValuePolicy: 'compute_only' }),
  field({ id: 'media.hero.summary', page: 'media', section: 'hero', label: 'Présentation principale', purpose: 'Résumer l’identité et les traits distinctifs de l’exemplaire.', instructions: 'Rédiger 2 à 4 phrases factuelles à partir des champs validés. Séparer les faits établis des éléments à confirmer et ne jamais ajouter de valeur marketing non sourcée.', dataType: 'long_text', cardinality: 'single', required: false, confidentiality: 'community', sourcePriority: ['document', 'expert', 'manufacturer', 'user'], validation: 'Aucune contradiction avec la référence, l’état ou les documents.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),

  field({ id: 'reference.origins.history[]', page: 'reference', section: 'origins', label: 'Historique du modèle', purpose: 'Présenter l’origine et la chronologie de la référence.', instructions: 'Rédiger un texte continu couvrant début et fin de production, variantes, références et volume produit lorsque ces données sont sourcées. Qualifier toute estimation.', dataType: 'long_text', cardinality: 'repeatable', required: false, confidentiality: 'public', sourcePriority: ['manufacturer', 'document', 'expert'], validation: 'Dates et nombres cités par une source ; absence de source explicitement signalée.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'reference.origins.knowledge', page: 'reference', section: 'origins', label: 'À savoir', purpose: 'Mettre en avant un fait utile à l’identification ou à l’authentification.', instructions: 'Sélectionner un point spécifique au modèle et utile au lecteur. Éviter l’anecdote générale sans impact documentaire.', dataType: 'long_text', cardinality: 'single', required: false, confidentiality: 'public', sourcePriority: ['manufacturer', 'expert', 'document'], validation: 'Fait vérifiable et cohérent avec les points de contrôle.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'reference.specifications[].label', page: 'reference', section: 'specifications', label: 'Nom de spécification', purpose: 'Nommer une caractéristique technique ou commerciale.', instructions: 'Réutiliser les catégories usuelles Chrono24 lorsqu’elles conviennent, sinon créer un libellé précis et non redondant.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'public', sourcePriority: ['manufacturer', 'document', 'expert', 'user'], validation: 'Libellé unique dans son groupe.', examples: ['Réserve de marche', 'Matériau de la lunette'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'reference.specifications[].value', page: 'reference', section: 'specifications', label: 'Valeur de spécification', purpose: 'Renseigner la valeur correspondant à une caractéristique.', instructions: 'Reprendre la valeur officielle avec son unité. En cas de divergence, conserver les sources et proposer la valeur la mieux étayée sans masquer le conflit.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'public', sourcePriority: ['manufacturer', 'document', 'expert', 'user'], validation: 'Unité incluse lorsque nécessaire ; correspond au libellé de la même instance.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'reference.checks[].checked', page: 'reference', section: 'checks', label: 'Résultat du contrôle', purpose: 'Indiquer si un point spécifique à cette montre a été physiquement ou documentairement vérifié.', instructions: 'Cocher seulement si une preuve directe permet de conclure. Une simple probabilité ou conformité attendue ne suffit pas.', dataType: 'boolean', cardinality: 'repeatable', required: true, confidentiality: 'community', sourcePriority: ['expert', 'document', 'user'], validation: 'Preuve référencée ; valeur fausse par défaut en l’absence de contrôle.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'reference.checks[].title', page: 'reference', section: 'checks', label: 'Point à contrôler', purpose: 'Définir un critère d’identification propre à l’exemplaire.', instructions: 'Formuler un contrôle précis, observable et spécifique à la référence ou au numéro de série.', dataType: 'text', cardinality: 'repeatable', required: true, confidentiality: 'community', sourcePriority: ['manufacturer', 'expert', 'document'], validation: 'Un seul critère par ligne ; pas de contrôle générique.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'reference.checks[].note', page: 'reference', section: 'checks', label: 'Mode de contrôle', purpose: 'Expliquer ce qui doit être observé et comment conclure.', instructions: 'Décrire l’indice attendu, la méthode et, si utile, le motif d’échec. Ne pas présenter le résultat comme acquis.', dataType: 'long_text', cardinality: 'repeatable', required: true, confidentiality: 'community', sourcePriority: ['expert', 'manufacturer', 'document'], validation: 'Consigne testable et liée au titre de la même instance.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'reference.popularity[].name', page: 'reference', section: 'popularity', label: 'Nom du site ou forum', purpose: 'Identifier une ressource consacrée au modèle ou à la marque.', instructions: 'Utiliser le nom éditorial de la ressource, sans slogan.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'public', sourcePriority: ['manufacturer', 'document', 'user'], validation: 'Nom cohérent avec l’URL.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'reference.popularity[].type', page: 'reference', section: 'popularity', label: 'Type de ressource', purpose: 'Qualifier la nature de la ressource.', instructions: 'Choisir le type selon la page cible et son éditeur, non selon sa popularité supposée.', dataType: 'enum', cardinality: 'repeatable', required: false, confidentiality: 'public', sourcePriority: ['document', 'user'], validation: 'Valeur comprise dans la liste autorisée.', allowedValues: ['Forum officiel', 'Discussion dédiée', 'Communauté', 'Base de données', 'Revue'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'reference.popularity[].url', page: 'reference', section: 'popularity', label: 'URL de la ressource', purpose: 'Permettre l’accès direct à la ressource.', instructions: 'Enregistrer l’URL canonique en HTTPS et vérifier qu’elle mène à la ressource décrite.', dataType: 'url', cardinality: 'repeatable', required: false, confidentiality: 'public', sourcePriority: ['document', 'user'], validation: 'URL absolue http(s), accessible et cohérente avec le nom.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),

  field({ id: 'condition.description.paragraphs[]', page: 'condition', section: 'description', label: 'Description de la montre', purpose: 'Décrire factuellement l’exemplaire observé.', instructions: 'Décrire configuration, apparence et éléments présents sans conclure sur l’authenticité ou la valeur sauf preuve explicite.', dataType: 'long_text', cardinality: 'repeatable', required: false, confidentiality: 'community', sourcePriority: ['expert', 'document', 'user'], validation: 'Aucune contradiction avec les médias et spécifications validés.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'condition.summary.paragraphs[]', page: 'condition', section: 'summary', label: 'Synthèse de l’état actuel', purpose: 'Résumer l’état de conservation et les points encore ouverts.', instructions: 'Distinguer observations, contrôles effectués et réserves. Mentionner la date du rapport utilisé.', dataType: 'long_text', cardinality: 'repeatable', required: false, confidentiality: 'community', sourcePriority: ['expert', 'document'], validation: 'Appuyé sur le rapport de référence ou une revue datée.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'condition.summary.lastCondition', page: 'condition', section: 'summary', label: 'Dernier état', purpose: 'Indiquer la date de la dernière revue pertinente.', instructions: 'Utiliser la date du rapport de référence le plus récent, pas la date d’import.', dataType: 'date', cardinality: 'single', required: false, confidentiality: 'community', sourcePriority: ['document', 'expert'], validation: 'Date ISO en stockage ; date non future sauf contrôle planifié explicitement.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'condition.summary.conclusion', page: 'condition', section: 'summary', label: 'Conclusion', purpose: 'Donner une conclusion courte sur l’état de la montre.', instructions: 'Résumer le niveau de conservation en quelques mots et garder les réserves dans le texte détaillé.', dataType: 'text', cardinality: 'single', required: false, confidentiality: 'community', sourcePriority: ['expert', 'document'], validation: 'Conclusion issue d’un rapport daté, sans surpromesse.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'condition.summary.openPoint', page: 'condition', section: 'summary', label: 'Point ouvert', purpose: 'Mettre en avant le principal contrôle restant.', instructions: 'Choisir le point non résolu le plus important pour l’identification, l’état ou l’entretien.', dataType: 'text', cardinality: 'single', required: false, confidentiality: 'community', sourcePriority: ['expert', 'document'], validation: 'Doit correspondre à une réserve documentée.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'condition.documentation[].category', page: 'condition', section: 'documentation', label: 'Catégorie de l’élément associé', purpose: 'Classer papier, documentation, assurance, boîte ou accessoire.', instructions: 'Choisir la catégorie qui décrit l’objet, indépendamment de son état.', dataType: 'enum', cardinality: 'repeatable', required: true, confidentiality: 'community', sourcePriority: ['document', 'user', 'expert'], validation: 'Valeur comprise dans la liste autorisée.', allowedValues: ['Facture', 'Garantie', 'Assurances', 'Boîte', 'Écrin', 'Manuel', 'Certificat', 'Accessoire', 'Autre'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'condition.documentation[].description', page: 'condition', section: 'documentation', label: 'Description de l’élément associé', purpose: 'Identifier précisément l’objet ou le document.', instructions: 'Décrire le contenu, les dates et les numéros utiles sans recopier des données personnelles inutiles.', dataType: 'long_text', cardinality: 'repeatable', required: false, confidentiality: 'community', sourcePriority: ['document', 'user', 'expert'], validation: 'Description cohérente avec les fichiers associés.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'condition.documentation[].state', page: 'condition', section: 'documentation', label: 'État de l’élément associé', purpose: 'Qualifier la présence et la complétude.', instructions: 'Choisir Présent ou Complet uniquement après contrôle ; utiliser À vérifier lorsqu’une preuve manque.', dataType: 'enum', cardinality: 'repeatable', required: true, confidentiality: 'community', sourcePriority: ['expert', 'document', 'user'], validation: 'Valeur comprise dans la liste autorisée.', allowedValues: ['Présent', 'Complet', 'Incomplet', 'Manquant', 'À vérifier'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'condition.reports[].date', page: 'condition', section: 'reports', label: 'Date du rapport ou de la revue', purpose: 'Ordonner l’historique de l’état.', instructions: 'Utiliser la date de l’examen ou du document, pas celle de son import.', dataType: 'date', cardinality: 'repeatable', required: true, confidentiality: 'community', sourcePriority: ['document', 'expert', 'file_metadata'], validation: 'Date ISO et cohérente avec les pièces jointes.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'condition.reports[].title', page: 'condition', section: 'reports', label: 'Titre du rapport ou de la revue', purpose: 'Identifier la nature et la période de l’entrée.', instructions: 'Nommer le document ou l’examen de façon courte, sans intégrer la conclusion dans le titre.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'community', sourcePriority: ['document', 'expert', 'user'], validation: 'Titre distinct et cohérent avec la date.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'condition.reports[].note', page: 'condition', section: 'reports', label: 'Note du rapport ou de la revue', purpose: 'Conserver les observations et conclusions pertinentes.', instructions: 'Résumer le document en séparant constats, mesures, interventions et réserves. Citer la pièce source.', dataType: 'long_text', cardinality: 'repeatable', required: false, confidentiality: 'community', sourcePriority: ['document', 'expert'], validation: 'Résumé fidèle ; pas de diagnostic ajouté sans source.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'condition.reports[].documents', page: 'condition', section: 'reports', label: 'Pièces jointes au rapport', purpose: 'Associer les preuves au rapport ou à la revue.', instructions: 'Importer les originaux, préserver métadonnées et empreintes, puis relier chaque pièce à la bonne entrée datée.', dataType: 'file', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user', 'file_metadata'], validation: 'Fichier lisible et relié à une entrée existante.', aiWritable: false, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),

  field({ id: 'value.market.analysisDate', page: 'value', section: 'market_depth', label: 'Date de l’analyse', purpose: 'Dater la photographie du marché utilisée pour la valorisation.', instructions: 'Utiliser la date d’arrêté de la collecte, pas la date de consultation ultérieure du dossier.', dataType: 'date', cardinality: 'single', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document', 'user'], validation: 'Date ISO, non postérieure aux observations utilisées.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.market.transactions12m', page: 'value', section: 'market_depth', label: 'Transactions identifiées sur 12 mois', purpose: 'Mesurer la profondeur du marché réalisé.', instructions: 'Compter les transactions distinctes et vérifiables sur les douze mois précédant la date d’analyse. Dédupliquer les republications.', dataType: 'number', cardinality: 'single', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document'], validation: 'Entier positif avec liste des transactions sources.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'value.market.valuations[].date', page: 'value', section: 'market_history', label: 'Date de valorisation', purpose: 'Dater une observation de l’évolution du marché.', instructions: 'Utiliser la date d’arrêté de l’échantillon correspondant.', dataType: 'date', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document'], validation: 'Date ISO et antérieure ou égale à la date d’analyse.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.market.valuations[].midValue', page: 'value', section: 'market_history', label: 'Valeur médiane', purpose: 'Conserver le point central d’une estimation datée.', instructions: 'Calculer à partir d’un échantillon documenté ou reprendre une évaluation datée ; ne pas confondre prix affiché et prix réalisé.', dataType: 'money', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document', 'calculation'], validation: 'Montant positif avec devise et méthode.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'value.retained.amount', page: 'value', section: 'retained_value', label: 'Valeur retenue', purpose: 'Conserver le montant choisi par le propriétaire comme valeur de référence du bien.', instructions: 'Initialiser avec la valeur actuelle, puis ne modifier que sur instruction explicite du propriétaire. Ne pas altérer les données de marché sous-jacentes.', dataType: 'money', cardinality: 'single', required: true, confidentiality: 'secret', sourcePriority: ['user', 'market'], validation: 'Montant positif dans la devise du dossier ; tout écart avec la valeur actuelle doit pouvoir être expliqué.', aiWritable: false, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.retained.explanation', page: 'value', section: 'retained_value', label: 'Explication de la valeur retenue', purpose: 'Documenter la logique, les ajustements et les réserves qui conduisent au montant retenu.', instructions: 'Expliquer les écarts par rapport à la valeur actuelle en distinguant état, complétude, liquidité, canal et décision patrimoniale.', dataType: 'long_text', cardinality: 'single', required: false, confidentiality: 'secret', sourcePriority: ['user', 'market', 'expert'], validation: 'Texte cohérent avec le montant retenu et les données de marché visibles.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.comparables[].date', page: 'value', section: 'comparables', label: 'Date du comparable', purpose: 'Dater l’annonce ou la transaction.', instructions: 'Utiliser la date de publication pour une annonce et la date de vente pour une transaction.', dataType: 'date', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document'], validation: 'Date ISO avec nature de date cohérente avec le canal.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.comparables[].description', page: 'value', section: 'comparables', label: 'Description du comparable', purpose: 'Identifier la montre comparable et ses différences pertinentes.', instructions: 'Inclure marque, modèle, référence, année, état et contenu livré lorsqu’ils sont connus. Ne pas masquer les écarts avec l’exemplaire.', dataType: 'long_text', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document'], validation: 'Description suffisante pour apprécier la comparabilité.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'value.comparables[].source', page: 'value', section: 'comparables', label: 'Source du comparable', purpose: 'Conserver la provenance vérifiable de l’observation.', instructions: 'Enregistrer le nom de la plateforme, maison de vente ou professionnel et l’URL ou identifiant source dans la provenance.', dataType: 'text', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document'], validation: 'Source nommée et traçable.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.comparables[].sourceType', page: 'value', section: 'comparables', label: 'Nature du comparable', purpose: 'Séparer annonces en cours et transactions réalisées.', instructions: 'Classer en Annonce uniquement si le prix est demandé ; classer en Transaction uniquement si le résultat de vente est confirmé.', dataType: 'enum', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document'], validation: 'Valeur comprise dans la liste autorisée.', allowedValues: ['Annonce', 'Transaction'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.comparables[].channel', page: 'value', section: 'comparables', label: 'Canal de vente', purpose: 'Qualifier le mécanisme de commercialisation.', instructions: 'Identifier le canal réellement utilisé, indépendamment de la source qui relaie le résultat.', dataType: 'enum', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document'], validation: 'Canal précis et cohérent avec la source.', allowedValues: ['Enchère', 'Annonce', 'Marchand', 'Privé', 'Autre'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'value.comparables[].condition', page: 'value', section: 'comparables', label: 'État du comparable', purpose: 'Mesurer l’impact de l’état et de la complétude sur le prix.', instructions: 'Reprendre l’état observé ou déclaré et préciser les papiers, boîte et service lorsqu’ils influencent la comparabilité.', dataType: 'text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['market', 'document', 'expert'], validation: 'Distinguer l’état déclaré de l’état expertisé.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'mark_unknown' }),
  field({ id: 'value.comparables[].amount', page: 'value', section: 'comparables', label: 'Montant du comparable', purpose: 'Conserver le prix demandé ou réalisé.', instructions: 'Saisir le montant brut observé et préciser dans la provenance si les frais acheteur, taxes ou commissions sont inclus.', dataType: 'money', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document'], validation: 'Montant positif avec devise et statut demandé/réalisé.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.comparables[].currency', page: 'value', section: 'comparables', label: 'Devise du comparable', purpose: 'Éviter toute ambiguïté de conversion.', instructions: 'Conserver la devise d’origine selon ISO 4217 ; effectuer toute conversion dans un champ ou calcul séparé et daté.', dataType: 'enum', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['market', 'document'], validation: 'Code devise ISO 4217.', examples: ['EUR', 'CHF', 'USD'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.comparables.analysis[]', page: 'value', section: 'comparables_analysis', label: 'Réflexion de marché', purpose: 'Synthétiser les enseignements sur les prix, canaux et liquidité.', instructions: 'Fonder chaque constat sur l’échantillon disponible, quantifier lorsque possible et expliciter les limites. Séparer prix affichés et réalisés.', dataType: 'long_text', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['calculation', 'market', 'expert'], validation: 'Chaque conclusion renvoie aux observations utilisées.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.purchase.date', page: 'value', section: 'cost_basis', label: 'Date d’achat', purpose: 'Dater le décaissement initial.', instructions: 'Reprendre la date de transfert ou de facture retenue pour le calcul, selon la politique du dossier.', dataType: 'date', cardinality: 'single', required: true, confidentiality: 'secret', sourcePriority: ['document', 'user'], validation: 'Date ISO et cohérente avec la facture.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.purchase.price', page: 'value', section: 'cost_basis', label: 'Valeur d’achat', purpose: 'Conserver le prix d’acquisition initial.', instructions: 'Saisir le montant effectivement payé pour la montre, hors dépenses postérieures déjà enregistrées séparément.', dataType: 'money', cardinality: 'single', required: true, confidentiality: 'secret', sourcePriority: ['document', 'user'], validation: 'Montant positif, devise du dossier et rapprochement avec la facture.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.expenses[].kind', page: 'value', section: 'cost_basis', label: 'Type de dépense', purpose: 'Classer les coûts de détention et de conservation.', instructions: 'Choisir la catégorie économique principale de la dépense.', dataType: 'enum', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['document', 'user'], validation: 'Valeur comprise dans la liste autorisée.', allowedValues: ['Révision', 'Assurance', 'Coûts de conservation', 'Autre'], aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.expenses[].date', page: 'value', section: 'cost_basis', label: 'Date de dépense', purpose: 'Dater le flux utilisé dans le prix de revient et le TRI.', instructions: 'Utiliser la date de paiement ou de facture selon la convention appliquée de manière constante.', dataType: 'date', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['document', 'user'], validation: 'Date ISO et pièce source conservée.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.expenses[].label', page: 'value', section: 'cost_basis', label: 'Libellé de dépense', purpose: 'Expliquer précisément la nature du coût.', instructions: 'Nommer le fournisseur, la période ou l’objet utile sans recopier une phrase commerciale.', dataType: 'text', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['document', 'user'], validation: 'Libellé distinct et cohérent avec le type.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.expenses[].amount', page: 'value', section: 'cost_basis', label: 'Montant de dépense', purpose: 'Inclure le coût dans le prix de revient.', instructions: 'Saisir le montant effectivement payé, net des remboursements, dans la devise du dossier.', dataType: 'money', cardinality: 'repeatable', required: true, confidentiality: 'secret', sourcePriority: ['document', 'user'], validation: 'Montant positif et rapproché d’une pièce ou d’une déclaration.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.exit.saleDate', page: 'value', section: 'performance', label: 'Date de vente', purpose: 'Fixer la date du flux de cession pour le TRI.', instructions: 'Utiliser la date d’une vente réalisée ou une date d’hypothèse explicitement qualifiée comme telle.', dataType: 'date', cardinality: 'single', required: true, confidentiality: 'secret', sourcePriority: ['user', 'document'], validation: 'Date postérieure ou égale à la date d’achat.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.exit.salePrice', page: 'value', section: 'performance', label: 'Prix de vente', purpose: 'Fixer le produit brut de cession.', instructions: 'Utiliser le prix réalisé ou une hypothèse issue de la valorisation, en conservant clairement son statut.', dataType: 'money', cardinality: 'single', required: true, confidentiality: 'secret', sourcePriority: ['document', 'market', 'user'], validation: 'Montant positif dans la devise du dossier.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.exit.disposalCostPct', page: 'value', section: 'performance', label: 'Coût de cession', purpose: 'Modéliser commissions et frais de vente en pourcentage.', instructions: 'Utiliser le taux contractuel du canal envisagé ou une hypothèse documentée. Indiquer clairement ce qui est inclus.', dataType: 'percentage', cardinality: 'single', required: true, confidentiality: 'secret', sourcePriority: ['document', 'market', 'user'], validation: 'Pourcentage compris entre 0 et 100.', aiWritable: true, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'value.computed.costBasis', page: 'value', section: 'calculations', label: 'Prix de revient', purpose: 'Additionner prix d’achat et dépenses retenues.', instructions: 'Calculer uniquement à partir des entrées validées ; ne jamais proposer une valeur indépendante.', dataType: 'computed', cardinality: 'computed', required: true, confidentiality: 'secret', sourcePriority: ['calculation'], validation: 'Somme reproductible des flux inclus.', dependencies: ['value.purchase.price', 'value.expenses[].amount'], aiWritable: false, humanReviewRequired: false, emptyValuePolicy: 'compute_only' }),
  field({ id: 'value.computed.capitalGainLoss', page: 'value', section: 'calculations', label: 'Plus-value ou moins-value nette', purpose: 'Mesurer la différence entre produit net et prix de revient.', instructions: 'Calculer automatiquement à partir du prix de vente, du coût de cession et du prix de revient.', dataType: 'computed', cardinality: 'computed', required: true, confidentiality: 'secret', sourcePriority: ['calculation'], validation: 'Calcul reproductible avec signe conservé.', dependencies: ['value.exit.salePrice', 'value.exit.disposalCostPct', 'value.computed.costBasis'], aiWritable: false, humanReviewRequired: false, emptyValuePolicy: 'compute_only' }),
  field({ id: 'value.computed.irr', page: 'value', section: 'calculations', label: 'TRI annualisé', purpose: 'Mesurer la performance annualisée sur des flux datés.', instructions: 'Calculer par XIRR sur les flux validés ; retourner non calculable si les conditions mathématiques ne sont pas réunies.', dataType: 'computed', cardinality: 'computed', required: true, confidentiality: 'secret', sourcePriority: ['calculation'], validation: 'Au moins un flux négatif, un flux positif et des dates valides.', dependencies: ['value.purchase.date', 'value.purchase.price', 'value.expenses[].date', 'value.expenses[].amount', 'value.exit.saleDate', 'value.exit.salePrice', 'value.exit.disposalCostPct'], aiWritable: false, humanReviewRequired: false, emptyValuePolicy: 'compute_only' }),
  field({ id: 'value.computed.sensitivity', page: 'value', section: 'calculations', label: 'Tableaux de sensibilité', purpose: 'Comparer plus-value et TRI selon prix de vente et coût de cession.', instructions: 'Recalculer chaque cellule à partir des hypothèses de ligne et colonne ; ne jamais saisir les résultats manuellement.', dataType: 'computed', cardinality: 'computed', required: true, confidentiality: 'secret', sourcePriority: ['calculation'], validation: 'Chaque cellule est reproductible par la même formule.', dependencies: ['value.computed.costBasis', 'value.exit.saleDate'], aiWritable: false, humanReviewRequired: false, emptyValuePolicy: 'compute_only' }),

  field({ id: 'publishing.blocks.website', page: 'publishing', section: 'selection', label: 'Sélection Watch website', purpose: 'Choisir les blocs visibles sur l’URL publique indépendante.', instructions: 'Décision exclusivement humaine. L’IA peut signaler les risques de confidentialité mais ne doit jamais activer W.', dataType: 'boolean', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user'], validation: 'Activation explicite par un utilisateur autorisé.', aiWritable: false, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
  field({ id: 'publishing.blocks.report', page: 'publishing', section: 'selection', label: 'Sélection Rapport PDF', purpose: 'Choisir les blocs inclus dans le rapport imprimable.', instructions: 'Décision exclusivement humaine. L’IA peut recommander une sélection mais ne doit jamais activer R.', dataType: 'boolean', cardinality: 'repeatable', required: false, confidentiality: 'secret', sourcePriority: ['user'], validation: 'Activation explicite par un utilisateur autorisé.', aiWritable: false, humanReviewRequired: true, emptyValuePolicy: 'leave_blank' }),
] as const;

export type AIFieldId = (typeof AI_FIELD_CATALOG)[number]['id'];

export const AI_FIELD_CATALOG_BY_ID: Readonly<Record<AIFieldId, (typeof AI_FIELD_CATALOG)[number]>> =
  Object.fromEntries(AI_FIELD_CATALOG.map((descriptor) => [descriptor.id, descriptor])) as Record<AIFieldId, (typeof AI_FIELD_CATALOG)[number]>;

export const getAIFieldDescriptor = (id: AIFieldId) => AI_FIELD_CATALOG_BY_ID[id];

export const aiFieldProps = (id: AIFieldId, instance?: string | number) => ({
  'data-ai-field': id,
  'data-ai-instance': instance === undefined ? undefined : String(instance),
  'data-ai-schema-version': AI_SCHEMA_VERSION,
});

export interface AIFillProposal {
  fieldId: AIFieldId;
  instanceId?: string;
  operation: 'set' | 'append' | 'tag' | 'remove' | 'skip';
  value: unknown;
  sourceRefs: string[];
  confidence: number;
  rationale: string;
  observedAt: string;
  requiresHumanReview: true;
}

export const AI_AUTOFILL_POLICY = {
  mode: 'proposal_only',
  rules: [
    'Ne jamais écraser silencieusement une valeur existante ou validée.',
    'Fournir au moins une source traçable pour toute proposition factuelle.',
    'Ne jamais inventer : utiliser skip ou laisser vide lorsque la preuve est insuffisante.',
    'Distinguer les faits observés, les déclarations, les estimations et les calculs.',
    'Conserver la date, la provenance, la confiance et les conflits de chaque proposition.',
    'Garder les données du propriétaire et du stockage au niveau Secret par défaut.',
    'Ne jamais écrire directement un champ calculé ; modifier uniquement ses entrées.',
    'Extraire les horodatages et empreintes des médias par le pipeline technique dédié.',
    'Soumettre tout conflit ou proposition à une validation humaine avant enregistrement.',
    'Ne jamais activer les marqueurs W ou R à la place de l’utilisateur.',
  ],
  confidence: {
    high: 0.85,
    review: 0.6,
    belowReview: 'skip',
  },
} as const;
