import {
  CARTULARY_MODEL_VERSION,
  type CartularyImportBundle,
} from '../domain/cartulary.ts';
import { importedProvenance } from './importHelpers.ts';

export const CAR_DEMO_CARTULARY_ID = 'cart_car_demo_gt_1987';
export const CAR_DEMO_IMPORT_REQUEST_ID = 'wave4-import-car-demo-v1';
export const CAR_DEMO_IMPORT_SOURCE_ID = 'source_wave4_car_fixture';
export const CAR_DEMO_IMPORT_ACTOR_ID = 'wave1-owner';
export const CAR_DEMO_IMPORT_DATE = '2026-08-14T14:00:00.000Z';

const provenance = <T>(value: T, observedAt = CAR_DEMO_IMPORT_DATE) => importedProvenance({
  value,
  sourceId: CAR_DEMO_IMPORT_SOURCE_ID,
  observedAt,
  assertedBy: 'migration:wave4-car-fixture',
});

export const buildCarDemoImportBundle = (): CartularyImportBundle => ({
  envelope: {
    id: CAR_DEMO_CARTULARY_ID,
    organizationId: 'org_demo',
    registryId: 'reg_collection_privee',
    collectionId: 'col_vehicles',
    assetType: 'car',
    schemaId: 'car',
    schemaVersion: '1.0.0',
    publicCode: 'CAR-DEMO-01',
    displayTitle: 'Voiture pilote multi-actifs',
    makerName: 'Constructeur Démonstration',
    modelName: 'GT',
    referenceCode: 'DEMO-GT-1987',
    manufactureYear: 1987,
    accountHolderId: CAR_DEMO_IMPORT_ACTOR_ID,
    legalOwnerRelationId: 'owner_relation_car_demo_current',
    lifecycleStatus: 'review',
    possessionStatus: 'in_possession',
    defaultVisibility: 'secret',
    publicationStatus: 'none',
    primaryAssetId: null,
    completenessLevel: 'imported_unreviewed',
    lastVerifiedAt: null,
    revision: 1,
    integrityHead: '',
    integritySequence: 0,
    modelVersion: CARTULARY_MODEL_VERSION,
    deletedAt: null,
  },
  sections: [
    {
      id: 'identity.summary',
      schemaSectionId: 'cover.car',
      schemaVersion: 'car@1.0.0',
      title: 'Identité du véhicule',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'cover.asset.type': provenance('Voiture'),
        'cover.car.maker': provenance('Constructeur Démonstration'),
        'cover.car.model': provenance('GT'),
        'cover.car.version': provenance('Pilote 2.0'),
        'cover.car.year': provenance(1987),
      },
      revision: 1,
    },
    {
      id: 'identity.private',
      schemaSectionId: 'identity.private',
      schemaVersion: 'car@1.0.0',
      title: 'Identifiants confidentiels',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'identity.car.vin': provenance(null),
        'identity.car.registration': provenance(null),
      },
      revision: 1,
    },
    {
      id: 'technical.powertrain',
      schemaSectionId: 'technical.powertrain',
      schemaVersion: 'car@1.0.0',
      title: 'Motorisation et transmission',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'technical.engine.architecture': provenance('4 cylindres en ligne — donnée de démonstration'),
        'technical.engine.displacementCc': provenance(1998),
        'technical.engine.fuelType': provenance('Essence'),
        'technical.engine.powerKw': provenance(110),
        'technical.engine.powerHp': provenance(150),
        'technical.transmission.gearbox': provenance('Manuelle — donnée de démonstration'),
        'technical.transmission.drivetrain': provenance('Propulsion'),
      },
      revision: 1,
    },
    {
      id: 'technical.chassis',
      schemaSectionId: 'technical.chassis',
      schemaVersion: 'car@1.0.0',
      title: 'Châssis et carrosserie',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'technical.chassis.code': provenance('DEMO-CHASSIS'),
        'technical.chassis.bodyStyle': provenance('Coupé'),
      },
      extensions: {
        'future.car.telemetry.health': provenance('Non évalué — fallback vague 4'),
      },
      revision: 1,
    },
    {
      id: 'usage.current',
      schemaSectionId: 'usage.current',
      schemaVersion: 'car@1.0.0',
      title: 'Usage courant',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'usage.mileage.valueKm': provenance(12345),
        'usage.mileage.observedAt': provenance('2026-08-14'),
        'usage.roadworthiness.status': provenance('Inconnu'),
        'usage.roadworthiness.expiresAt': provenance(null),
      },
      revision: 1,
    },
    {
      id: 'condition.current',
      schemaSectionId: 'condition.current',
      schemaVersion: 'car@1.0.0',
      title: 'État du véhicule',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'condition.body.summary': provenance('Aucune inspection réelle — fixture de construction.'),
        'condition.interior.summary': provenance('Aucune inspection réelle — fixture de construction.'),
        'condition.mechanical.summary': provenance('Aucune inspection réelle — fixture de construction.'),
        'condition.tires.summary': provenance('Aucune inspection réelle — fixture de construction.'),
        'condition.corrosion.summary': provenance('Aucune inspection réelle — fixture de construction.'),
        'condition.overall.conclusion': provenance('État non évalué ; revue humaine obligatoire.'),
      },
      revision: 1,
    },
    {
      id: 'history.service',
      schemaSectionId: 'history.service',
      schemaVersion: 'car@1.0.0',
      title: 'Historique d’entretien',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'history.service[].date': [],
        'history.service[].mileageKm': [],
        'history.service[].kind': [],
        'history.service[].description': [],
        'history.incidents[].summary': [],
      },
      revision: 1,
    },
    {
      id: 'value.retained',
      schemaSectionId: 'value.retained',
      schemaVersion: 'car@1.0.0',
      title: 'Valeur de travail',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'value.market.analysisDate': provenance('2026-08-14'),
        'value.retained.amount': provenance({ amount: null, currency: 'EUR' }),
        'value.retained.explanation': provenance('Aucune valeur réelle : fixture technique multi-actifs.'),
      },
      revision: 1,
    },
  ],
  sources: [
    {
      id: CAR_DEMO_IMPORT_SOURCE_ID,
      kind: 'project_document',
      label: 'Fixture technique vague 4 — aucune donnée patrimoniale réelle',
      locator: 'src/migrations/carDemoImport.ts',
      proofStatus: 'unverified',
      visibility: 'secret',
    },
  ],
  assets: [],
  spinSets: [],
  observations: [],
  valuations: [],
  comparables: [],
  reports: [],
  reminders: [],
  ownerRelations: [
    {
      id: 'owner_relation_car_demo_current',
      cartularyId: CAR_DEMO_CARTULARY_ID,
      organizationId: 'org_demo',
      userId: CAR_DEMO_IMPORT_ACTOR_ID,
      relationType: 'legal_owner',
      status: 'pending_evidence',
      validFrom: CAR_DEMO_IMPORT_DATE,
      validUntil: null,
      proofStatus: 'unverified',
      sourceRefs: [CAR_DEMO_IMPORT_SOURCE_ID],
      visibility: 'secret',
    },
  ],
  events: [
    {
      id: 'event_car_demo_imported',
      cartularyId: CAR_DEMO_CARTULARY_ID,
      organizationId: 'org_demo',
      eventType: 'migration.fixture_imported',
      occurredAt: CAR_DEMO_IMPORT_DATE,
      actorId: CAR_DEMO_IMPORT_ACTOR_ID,
      summary: 'Import de la fixture voiture pour tester le noyau multi-actifs.',
      sourceRefs: [CAR_DEMO_IMPORT_SOURCE_ID],
      proofStatus: 'unverified',
      visibility: 'secret',
    },
  ],
});
