import { mockCartulary } from '../data/mockData.ts';
import {
  CARTULARY_MODEL_VERSION,
  type CartularyImportBundle,
  type CartularyVisibility,
} from '../domain/cartulary.ts';
import { IWC_CARTULARY_ID } from '../domain/cartularyIds.ts';
import { importedProvenance } from './importHelpers.ts';

export { IWC_CARTULARY_ID };
export const IWC_IMPORT_REQUEST_ID = 'wave2-import-iwc-v1';
export const IWC_IMPORT_SOURCE_ID = 'source_prototype_mock_data';
export const IWC_IMPORT_ACTOR_ID = 'wave1-owner';
export const IWC_IMPORT_DATE = '2026-08-14T08:00:00.000Z';

const visibilityMap: Record<string, CartularyVisibility> = {
  Secret: 'secret',
  Communauté: 'community',
  Tous: 'public',
};

const provenance = <T>(value: T, observedAt = IWC_IMPORT_DATE) => importedProvenance({
  value,
  sourceId: IWC_IMPORT_SOURCE_ID,
  observedAt,
  assertedBy: 'migration:prototype-antigravity',
});

const watch = mockCartulary.watchInstance;
const primaryAsset = mockCartulary.assets.find((asset) => asset.tags.includes('main-photo'));

export const buildIwcImportBundle = (): CartularyImportBundle => ({
  envelope: {
    id: IWC_CARTULARY_ID,
    organizationId: 'org_demo',
    registryId: 'reg_collection_privee',
    collectionId: 'col_pilots',
    assetType: 'watch',
    schemaId: 'watch',
    schemaVersion: '1.3.0',
    publicCode: mockCartulary.publicCode,
    displayTitle: 'IWC Flieger UTC',
    makerName: watch.reference.brand,
    modelName: watch.reference.model,
    referenceCode: watch.reference.reference,
    manufactureYear: 2002,
    accountHolderId: IWC_IMPORT_ACTOR_ID,
    legalOwnerRelationId: 'owner_relation_iwc_current',
    lifecycleStatus: 'review',
    possessionStatus: 'in_possession',
    defaultVisibility: 'secret',
    publicationStatus: 'none',
    primaryAssetId: primaryAsset?.id ?? null,
    completenessLevel: 'imported_unreviewed',
    lastVerifiedAt: null,
    revision: 1,
    integrityHead: '',
    integritySequence: 0,
    modelVersion: CARTULARY_MODEL_VERSION,
    deletedAt: null,
  },
  sections: [
    {
      id: 'identity.summary',
      schemaSectionId: 'cover.watch',
      schemaVersion: 'watch@1.3.0',
      title: 'Identité de la montre',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'cover.asset.type': provenance('Montre'),
        'cover.watch.brand': provenance(watch.reference.brand),
        'cover.watch.model': provenance(watch.reference.model),
        'cover.watch.reference': provenance(watch.reference.reference),
        'cover.watch.status': provenance('Patrimonial'),
      },
      revision: 1,
    },
    {
      id: 'watch.reference',
      schemaSectionId: 'reference.specifications',
      schemaVersion: 'watch@1.3.0',
      title: 'Spécifications de référence',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'reference.specifications[].label': [
          provenance('Calibre'),
          provenance('Réserve de marche'),
          provenance('Matériau'),
          provenance('Diamètre'),
          provenance('Épaisseur'),
          provenance('Étanchéité'),
        ],
        'reference.specifications[].value': [
          provenance(watch.reference.caliber),
          provenance(watch.reference.powerReserve),
          provenance(watch.reference.material),
          provenance(`${watch.reference.diameter} mm`),
          provenance(`${watch.reference.thickness} mm`),
          provenance(watch.reference.waterResistance),
        ],
      },
      revision: 1,
    },
    {
      id: 'watch.instance.private',
      schemaSectionId: 'watch.instance.private',
      schemaVersion: 'watch@1.3.0',
      title: 'Identité confidentielle de l’exemplaire',
      visibility: 'secret',
      status: 'imported_unmapped',
      fields: {},
      extensions: {
        'legacy.watchInstance.serialNumber': provenance(watch.serialNumber),
      },
      revision: 1,
    },
    {
      id: 'value.purchase',
      schemaSectionId: 'value.cost_basis',
      schemaVersion: 'watch@1.3.0',
      title: 'Acquisition',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'value.purchase.date': provenance(watch.acquisitionDate, `${watch.acquisitionDate}T00:00:00.000Z`),
        'value.purchase.price': provenance({ amount: watch.acquisitionPrice ?? null, currency: watch.currency ?? null }),
      },
      revision: 1,
    },
    {
      id: 'storage.current',
      schemaSectionId: 'cover.storage',
      schemaVersion: 'watch@1.3.0',
      title: 'Conservation',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'cover.storage.locations[].name': [provenance(mockCartulary.location.storageType)],
        'cover.storage.locations[].contents': [provenance('Montre et accessoires documentés')],
        'cover.storage.locations[].description': [
          provenance(`${mockCartulary.location.city}, ${mockCartulary.location.country}`),
        ],
      },
      revision: 1,
    },
    {
      id: 'condition.summary',
      schemaSectionId: 'condition.summary',
      schemaVersion: 'watch@1.3.0',
      title: 'État importé',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'condition.summary.paragraphs[]': mockCartulary.conditionReports.map((report) => provenance(report.summary)),
        'condition.summary.lastCondition': provenance(mockCartulary.conditionReports.at(-1)?.date ?? null),
        'condition.summary.conclusion': provenance('Import technique à faire valider par le propriétaire ou un expert.'),
        'condition.summary.openPoint': provenance('Toutes les assertions et pièces restent non vérifiées après migration.'),
      },
      revision: 1,
    },
    {
      id: 'value.retained',
      schemaSectionId: 'value.retained_value',
      schemaVersion: 'watch@1.3.0',
      title: 'Valeur de travail',
      visibility: 'secret',
      status: 'imported_unreviewed',
      fields: {
        'value.market.analysisDate': provenance(mockCartulary.marketSnapshot.date),
        'value.retained.amount': provenance({
          amount: mockCartulary.marketSnapshot.midValue,
          currency: mockCartulary.marketSnapshot.currency,
        }),
        'value.retained.explanation': provenance('Valeur importée du prototype ; analyse de marché et sources à revalider.'),
      },
      revision: 1,
    },
  ],
  sources: [
    {
      id: IWC_IMPORT_SOURCE_ID,
      kind: 'prototype_migration',
      label: 'Prototype Antigravity — mockCartulary',
      locator: 'src/data/mockData.ts',
      proofStatus: 'unverified',
      visibility: 'secret',
    },
  ],
  assets: mockCartulary.assets.map((asset) => ({
    id: asset.id,
    cartularyId: IWC_CARTULARY_ID,
    organizationId: 'org_demo',
    originalVersionId: null,
    mediaKind: asset.type,
    displayName: asset.name,
    mimeDeclared: asset.mimeType ?? null,
    mimeDetected: null,
    sizeBytes: null,
    sha256: null,
    capturedAt: asset.capturedAt ?? null,
    timestampSource: asset.timestampSource ?? null,
    tags: [...asset.tags],
    componentCode: asset.category ?? null,
    evidencePurpose: 'prototype_migration',
    processingState: 'pending_binary_reingest',
    visibility: 'secret',
    requestedVisibility: visibilityMap[asset.visibility] ?? 'secret',
    sourceRefs: [IWC_IMPORT_SOURCE_ID],
    accessPolicyVersion: 'wave2-deny-all',
  })),
  spinSets: mockCartulary.spinSet
    ? [
        {
          id: mockCartulary.spinSet.id,
          cartularyId: IWC_CARTULARY_ID,
          organizationId: 'org_demo',
          assetIds: mockCartulary.spinSet.images.map((asset) => asset.id),
          angles: [...mockCartulary.spinSet.angles],
          posterAssetId: primaryAsset?.id ?? null,
          manifestHash: null,
          isComplete: false,
          visibility: 'secret',
          publicationState: 'blocked_pending_binaries',
        },
      ]
    : [],
  observations: watch.observations.map((observation) => ({
    id: observation.id,
    cartularyId: IWC_CARTULARY_ID,
    component: observation.component,
    description: observation.description,
    assetId: observation.assetId ?? null,
    proofStatus: 'unverified',
    importedProofStatus: observation.proofStatus,
    confidence: 'low',
    sourceRefs: [IWC_IMPORT_SOURCE_ID],
    observedAt: `${observation.date}T00:00:00.000Z`,
    visibility: 'secret',
    reviewStatus: 'pending_human_review',
  })),
  valuations: watch.valuations.map((valuation) => ({
    id: valuation.id,
    cartularyId: IWC_CARTULARY_ID,
    observedAt: `${valuation.date}T00:00:00.000Z`,
    lowValue: valuation.lowValue,
    midValue: valuation.midValue,
    highValue: valuation.highValue,
    currency: valuation.currency,
    sourceLabel: valuation.source,
    sourceRefs: [IWC_IMPORT_SOURCE_ID],
    proofStatus: 'unverified',
    confidence: 'low',
    visibility: 'secret',
    reviewStatus: 'pending_human_review',
  })),
  comparables: mockCartulary.comparables.map((comparable) => ({
    id: comparable.id,
    cartularyId: IWC_CARTULARY_ID,
    observedAt: `${comparable.date}T00:00:00.000Z`,
    channel: comparable.channel,
    description: comparable.description,
    amount: comparable.amount,
    currency: comparable.currency,
    condition: comparable.condition,
    sourceType: comparable.sourceType,
    saleChannel: comparable.saleChannel,
    sourceLabel: comparable.source,
    sourceRefs: [IWC_IMPORT_SOURCE_ID],
    proofStatus: 'unverified',
    confidence: 'low',
    visibility: 'secret',
    reviewStatus: 'pending_human_review',
  })),
  reports: mockCartulary.conditionReports.map((report) => ({
    id: report.id,
    cartularyId: IWC_CARTULARY_ID,
    observedAt: `${report.date}T00:00:00.000Z`,
    title: report.title,
    score: report.score,
    summary: report.summary,
    dossierId: report.dossierId,
    sourceRefs: [IWC_IMPORT_SOURCE_ID],
    proofStatus: 'unverified',
    visibility: 'secret',
    reviewStatus: 'pending_human_review',
  })),
  reminders: watch.reminders.map((reminder: { id: string; title: string; dueDate: string; status: string; category?: string }) => ({
    id: reminder.id,
    cartularyId: IWC_CARTULARY_ID,
    organizationId: 'org_demo',
    title: reminder.title,
    category: reminder.category || 'custom',
    dueAt: `${reminder.dueDate}T00:00:00.000Z`,
    reminderStatus: reminder.status.toLowerCase(),
    visibility: 'secret',
  })),
  ownerRelations: [
    {
      id: 'owner_relation_iwc_current',
      cartularyId: IWC_CARTULARY_ID,
      organizationId: 'org_demo',
      userId: IWC_IMPORT_ACTOR_ID,
      relationType: 'legal_owner',
      status: 'pending_evidence',
      validFrom: IWC_IMPORT_DATE,
      validUntil: null,
      proofStatus: 'unverified',
      sourceRefs: [IWC_IMPORT_SOURCE_ID],
      visibility: 'secret',
    },
  ],
  events: [
    {
      id: 'event_iwc_imported',
      cartularyId: IWC_CARTULARY_ID,
      organizationId: 'org_demo',
      eventType: 'migration.imported',
      occurredAt: IWC_IMPORT_DATE,
      actorId: IWC_IMPORT_ACTOR_ID,
      summary: 'Import technique du dossier IWC depuis le prototype Antigravity.',
      sourceRefs: [IWC_IMPORT_SOURCE_ID],
      proofStatus: 'unverified',
      visibility: 'secret',
    },
  ],
});
